### ISSUE TITLE
Linking from overlay to anchors

### ISSUE THREAD

**Issue by edmullen** [vast-engineering/jquery-popup-overlay#21]
Hello.

I have started using this plugin and wonder if something is possible. I am building a very long page with many sections. I'm implementing a table of contents in the overlay with anchor links to all the sections. I currently have simple links to the sections and see the page scrolling underneath on click. This does not close the overlay, however. But, what I would ideally like is to make the links _first_ trigger the window to close and then _onclose_ navigate to the anchor, preferably with an animation. I'd like the scroll to happen after the overlay closes because I have scrolllock set to true, and there is a jump that happens due to the scrollbar disappearing and reappearing. 

Thanks!

**Comment by vladimirsiljkovic** [comment]
Hi @edmullen,

It is possible with a little bit of additional javascript. Here's a demo, I think this is what you need:
http://jsbin.com/woyiyuxe/5

You can also use 'onclose' instead of 'closetransitionend' event you you want a scrolling to in parallel with closing animation.

Jumping scrollbar when 'scrolllock' option is set to true should be fixed with the latest commit.

Thanks!

**Comment by edmullen** [comment]
Thanks for taking the time to help, Vladimir!

That's exactly what I was looking for. You can see what I'm working on
here: http://clients.edmullen.com/terrapin/report.html It's still in
progress, but if you click on the "Sections" button in the upper right
you'll see the overlay.

Ed

---

*Edward Mullen Studio *
Phone: 201.743.9347
Website http://www.edmullen.com/ -
LinkedInhttp://www.linkedin.com/in/edwardmullen
- Twitter http://www.twitter.com/edmullen
