### ISSUE TITLE
Reference to the Popup ID or object

### ISSUE THREAD

**Issue by drebbits** [vast-engineering/jquery-popup-overlay#26]
Hi, Is there any way to reference the popup id ( or the popup object as variable) inside the callback functions?

```
$('#my_popup').popup({
 transition: 'all 0.2s',
 onopen: function(popup) {
    /* Sample scenario only. I added sample methods */
    /*  popup.id - Gets the ID name */ 
    var img_content = $('.'+popup.id'+_open').html();

    /* Dynamically gets the content from the _open element and add it to the my_popup overlay content */
   popup.content (img_content);
 }
});
```

**Comment by LordZardeck** [comment]
Well, `this` is a reference to the DOM element inside the callback. So if you needed the id you could just do `$(this).attr('id')`

**Comment by vladimirsiljkovic** [comment]
Hi Dreb,

I think this is what you need and it can be accomplished without a reference to a popup: http://jsfiddle.net/M5Pe6/4/

However, I've modified the plugin in order to be able to reference popup DOM object if passed as a first parameter, popup opening link DOM object if passed as a second parameter, and popup jQuery object as `this`.

Here's the example:

```
  $('#my_tooltip').popup({
      beforeopen: function(popup, link) {

          // popup = $('#my_tooltip')[0]
          // link = $('#my_tooltip_open')[0]
          // this =  $('#my_tooltip')

          var img_content = $(link).html();
          $(popup).html(img_content);

           // you can also access plugin methods e.g.:
           // this.popup('hide');
      }
  });
```

Here's a demo:

http://jsbin.com/makajini/34/edit

Hope this helps, thanks for reporting!

**Comment by drebbits** [comment]
Thanks Vlad! 

I actually went ahead and implemented it right away.

Cheers!
