### ISSUE TITLE
facebook iframe position issue.

### ISSUE THREAD

**Issue by xcasex** [vast-engineering/jquery-popup-overlay#5]
when inside iframe, it does not position and scroll to top of "document".
is there a workaround?

**Comment by vladimirsiljkovic** [comment]
Hi @xcasex,

Sorry for late response. Can you please provide more details or a demo page as I can't reproduce the issue.

I'm not sure if you are having issues with iframe inside of popup, or popup inside of iframe, so I've made a demo displaying both scenarios and it all seems to work correctly:

http://jsfiddle.net/GHGKp/5/

**Comment by vladimirsiljkovic** [comment]
I was able to reproduce the problem in my previous demo. It is visible if the browser window width is scaled down to be less than content's width (this is happening on mobile).

The fix is not to let popup content to exceed browser window width. In case of previous demo, the fix is to add `max-width: 100%;` to the iframe.

Here's the updated demo: http://jsfiddle.net/GHGKp/6/

The reason behind this is a drawback of this technique for centering CSS: http://css-tricks.com/centering-in-the-unknown/

If you must have fixed widths, you can fix the problem by vertically centering content with FlexBox ( http://philipwalton.github.io/solved-by-flexbox/demos/vertical-centering/ ), but you'll need to override inline styles with `!important`.

Thanks.
