### ISSUE TITLE
Re-initiate for mobile

### ISSUE THREAD

**Issue by bliitzkrieg** [vast-engineering/jquery-popup-overlay#51]
Hey was wondering if this is possible using this library - I want to have my tooltips to the right of my trigger on desktop and below my trigger on mobile. Is there a way to reinitiate the tooltips so the positioning gets set again or another way to accomplish this. 

I managed to make it work based on what device the user is using when they load the page using moderizr but if my user switches from portrait to landscape, the tooltips positions are messed up.

**Comment by vladimirsiljkovic** [comment]
Hi @bliitzkrieg,

It's possible to update tooltip options every time tooltip is opened, using plugin's callback event `beforeopen` combined with `Window.matchMedia()`, and you can also do some manual CSS modifications using media queries as well, by overriding inline styles with `!important` if needed.

Here's a demo (tooltip will appear below a trigger if the width of the screen is less than 750px, and additionally, using CSS overrides, the tooltip will have yellow background and 80% width below 480px screen size):
http://jsbin.com/nexireqeli/1/edit?html,css,js,output

Improved solution would be to reposition tooltips whenever window is resized (i.e. screen orientation is changed) because if the tooltip was visible before changing the screen orientation - it will adjust it's position automatically, so I've slightly modified the previous demo to include that:
http://jsbin.com/jeluqatoxu/1/edit?html,js,output

There might be some better/cleaner solution that I'm not aware of at this moment, an eventually we might implement some parts of this logic in the plugin, but for now you can do it this way.

Hope this helps.

Thanks.
