### ISSUE TITLE
IOS unclickable

### ISSUE THREAD

**Issue by ghost** [vast-engineering/jquery-popup-overlay#54]
This works great in all browsers and devices I've used except IOS, I'm using safari as standard, and have set up a very simple pop up. Now the demo on your site works on IOS, so is there any extra steps needed to enable on IOS?
I have included the site I've implemented this on, the CV icon should pop up with a CV, but no dice.

http://swhitedev.com/

**Comment by maryisdead** [comment]
You should first check your markup. There's some stuff going wrong and maybe it's mobile Safari choking up on it.

For example `<ul id='socialList'>` is missing `<li>`s and `<div id='my_popup'>` seems to be missing a closing tag.

[W3C Validator](https://validator.w3.org/check?uri=swhitedev.com&charset=%28detect+automatically%29&doctype=Inline&group=0) is your friend.

**Comment by ghost** [comment]
I've worked through the corrections you pointed me towards (thanks for the validator tool as well!) And the HTML does seem to be valid now, but no luck on IOS!  I also tested the popup with a standard button which worked! Is there an issue with the event firing from a span being clicked?

Thanks in advance!

**Comment by vladimirsiljkovic** [comment]
Yes, there is an issue in iOS with setting the click event handler to the parent of the HTML element that is not clickable by default (e.g. div, span, etc.). See http://stackoverflow.com/questions/3705937/document-click-not-working-correctly-on-iphone-jquery .

For example, this will not work:

```
$(document).on('click', 'span.my_popup_open', function(){
  alert('test');
});
```

This will work:

```
$('span.my_popup_open').on('click',  function(){
  alert('test');
});
```

You have two options:
1. Add `cursor: pointer;` to `<span>`.
2. Replace `<span>` with  `<button>` or `<a href="#my_popup">` or `<a href="javascript:;">`.

I'd recommend the second option because it's more accessible for keyboard users. If you use `<span>`, the popup cannot be opened using a keyboard (using TAB key).
