### ISSUE TITLE
using jquery-ui-datepicker on popup() is closing the popup

### ISSUE THREAD

**Issue by noamtahan** [vast-engineering/jquery-popup-overlay#72]
Hi,
I have input field on the popup content with field type text using jquery-ui-datepicker,
Clicking on the datepicker window is closing the popup window?
Why?
How can I prevent this issue?

demo
```

<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Site Title</title>
</head>
<body>

  <!-- Add an optional button to open the popup -->
  <button class="my_popup_open">Open popup</button>

  <!-- Add content to the popup -->
  <div id="my_popup">

<p>Date: <input type="text" id="datepicker"></p>

    <!-- Add an optional button to close the popup -->
    <button class="my_popup_close">Close</button>

  </div>

  <!-- Include jQuery -->
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>

  <!-- Include jQuery Popup Overlay -->
  <script src="https://cdn.rawgit.com/vast-engineering/jquery-popup-overlay/1.7.13/jquery.popupoverlay.js"></script>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <link rel="stylesheet" href="/resources/demos/style.css">
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <script>
  $( function() {
    $( "#datepicker" ).datepicker();
  } );
  </script>

  <script>
    $(document).ready(function() {

      // Initialize the plugin
      $('#my_popup').popup();
    $( "#datepicker" ).datepicker();

    });
  </script>

</body>
</html>

```
If I add blur: false, It is working, but I need the blur true.
code 
`
$('#my_popup').popup( {blur: false, });
`

**Comment by JVogel27** [comment]
I'm having this issue as well. I tried using the blur option set to false, like 

`$('#my_popup').popup({blur: false });`

But that did not work.

**Comment by pvgoran** [comment]
This happens because the datepicker's popup is, in terms of DOM, outside of the jquery-popup-overlay's popup (though it's logically and visually inside the latter). So jquery-popup-overlay code treats clicks on the datepicker's popup as "outside" clicks, closing the popup.

You can use the following code to prevent the issue:

```
      $(document).on('click', "#ui-datepicker-div", function(ev) {
        ev.stopPropagation();
      });
```

A more generic solution could be adding code to jquery-popup-overlay's `click` handler to check z-index of the clicked element, and don't close the popup if the z-index is greater than the popup's z-index. However, this can possibly have undesired side effects.

**Comment by vladimirsiljkovic** [comment]
A new option `blurignore` is added to the library (9464a57). The option accepts CSS selector as a value, and it will ignore the matched elements for the `blur` option logic. 

An example would be:

    $('#my_popup').popup({ blurignore: '#ui-datepicker-div' });
