### ISSUE TITLE
Popup will always showing the first one but what if there is more than one pop up

### ISSUE THREAD

**Issue by kenlu89** [vast-engineering/jquery-popup-overlay#88]
Let say if there is more than one pop up content. So a example HTML mark up will be. 

`<div id="my_popup">

    ...popup content...

    
    <button class="my_popup_close">Close</button>

  </div>
   <button class="my_popup_open">Open popup</button>

  
  <div id="my_popup">

    ...Second popup content ...

    
    <button class="my_popup_close">Close</button>

  </div>
`

How do we fix this if there is like more than one content. In my case i have like maybe 20 of them and it will just work on the first one but not rest of them. Example of code fix would be really appreciated. 

Thanks!

**Comment by pvgoran** [comment]
Just use different IDs for subsequent popups:

```
<button class="my_popup_2_open">Open popup</button>
<div id="my_popup_2">
    ...popup content...

    <!-- Add an optional button to close the popup -->
    <button class="my_popup_2_close">Close</button>
</div>
```

**Comment by smc-pt** [comment]
I'm having the same problem, but I'm not able to solve it with the suggestion above. 
When I just tried just one, it works great. 

I'm working with the "tooltip" option because I need the pop-up window to appear in a relative position to the links. I also have several things that need to happen: 

1. It needs to be accessible, so I'm using a link to open the tooltip, and a link to close it - no rollovers - this is already in the supplied code, so no problems there. 

2. I'm following an existing design, so my code incorporates several modifications to how the links look and the positions of the graphics on the page. Again, this didn't cause any problems when I was testing this out with only one on the page. 

Here's my code and where I'm getting stuck. The unordered list is placing each link in a column side by side, and only controls the layout and none of the functionality. The rest of the code is just pared down from the original demo files. 
```
<ul class="two-col cf">
	<li>
<div class="container">
	<p class="lineheight">
	<a href="#my_tooltip" class="initialism my_tooltip_open" id="my_tooltip_open"><span class="hfsr">More information on...</span></a>
	</p>
</div>

<div id="my_tooltip" class="well">
    <h2>Tooltip Example</h2>
    <p>Tooltip content will be positioned relative to the opening link.</p>
    <a href="#" class="my_tooltip_close"><span class="hfsr">Close Tool Tip</span></a>
</div>
&#160;
	</li>
	<li>
<div class="container">
	<p class="lineheight">
	<a href="#my_tooltip2" class="initialism my_tooltip_open" id="my_tooltip_open2"><span class="hfsr">More information on...</span></a>
	</p>
</div>

<div id="my_tooltip2" class="well">
    <h2>Tooltip Example 2</h2>
    <p>This is a second tool tip window.</p>
    <a href="#" class="my_tooltip_close"><span class="hfsr">Close Tool Tip</span></a>
</div>
&#160;
	</li>
</ul>	
	
<script>
$(document).ready(function () {

    $('#my_tooltip').popup({
        type: 'tooltip',
        vertical: 'bottom',
        horizontal: 'left',
        transition: '0.3s all 0.1s',
        tooltipanchor: $('#my_tooltip_open')
    });

    $('#my_tooltip2').popup({
        type: 'tooltip',
        vertical: 'bottom',
        horizontal: 'left',
        transition: '0.3s all 0.1s',
        tooltipanchor: $('#my_tooltip_open2')
    });

});
</script>
```
Each link opens the same tooltip window. I tried to remove the script for the first "my_tooltip" to see if the second one labeled "my_tooltip2" would function on it's own, but it doesn't. I've tried adding and removing the "2" in all sorts of combinations to no avail. I've tested it both locally and inside our CMS, and both behave the same way. 

Like kenlu89, I'm going to need several on the page. 

Here is a portion of my modified styles in case it helps. The links to the scripts are all in place.  

```
<style>

#my_tooltip,
#my_tooltip2	{
	width: 200px;
	position: relative;
}

.well	{
	background-color: #000;
	border: none;
}

.well h2	{
	font-size: 1.1em;
	font-weight: 600;
	color: #fff;
	margin-bottom: 5px;
}

.well p	{
	color: #fff;
	font-size: .9em;
}

.well a	{
	text-decoration: none;
	color: #fff;
}

a.initialism	{
	width: 16px;
	height: 16px;
	background-image: url('/TechnologyResources/Web/PublishingImages/Pop-Up-Test/info-icon.svg');
	background-position: -1px -1px;
	background-repeat: no-repeat;
	background-size: 18px 42px;
	display: block;
}

a.initialism:hover,
a.initialism:focus	{
	background-position: -1px -21px;	
}

a.my_tooltip_close	{
	width: 22px;
	height: 22px;
	background-image: url('/TechnologyResources/Web/PublishingImages/Pop-Up-Test/tool-tip-close-button.svg');
	background-position: -1px -1px;
	background-repeat: no-repeat;
	position: absolute;
	right: -8px;
	bottom: -8px;
	background-size: 22px 52px;
}

a.my_tooltip_close:hover,
a.my_tooltip_close:focus	{
	background-position: -1px -26px;	
}

</style>
```
Any help would be appreciated.

**Comment by vladimirsiljkovic** [comment]
@pvgoran answered correctly, thanks @pvgoran for your help!

@smc-pt, I've updated your code and it should be working now. Here's the demo: https://jsbin.com/pohozazeci/edit?html,css,output

- fix: updated the class name of the first opening link
- fix: updated the class name of the second closing link
- improvement: removed the `tooltipAnchor` option as it wasn't required for your case.
- improvement: added `display:none` to tooltips to prevent FOUC while loading the page

The class name of the opening and closing links/buttons should follow the ID of the popup with added `_open` or `_close` as suffix. The pattern is `.{ID}_open` for opening links or `.{ID}_close` for closing links.  For example, if a popup has `id=my_popup333`, the opening link(s) should be `class="my_popup333_open"` and the closing link should be `class="my_popup333_close"`.

**Comment by smc-pt** [comment]
Thanks for the help and instructions. 
Everything is working like a charm.

**Comment by vladimirsiljkovic** [comment]
Great, I'm glad it helped.

Here's another demo if someone needs: https://codepen.io/vladimirs/pen/gZbmyJ

Closing this one.
